spring:
  application:
    name: Dajanggan

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  batch:
    jdbc:
      initialize-schema: always
      platform: postgres
      table-prefix: BATCH_          # Postgres DDL과 일치시키기
    schema: public                # 테이블을 만들 스키마 지정 (기본 public)
server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.dajanggan.domains
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL
    default-fetch-size: 100
    default-statement-timeout: 30
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    lazy-loading-enabled: false
    aggressive-lazy-loading: false

logging:
  level:
    com.dajanggan: DEBUG
    com.dajanggan.domain.engine: DEBUG
    org.apache.ibatis: DEBUG
    com.zaxxer.hikari: INFO