spring:
  application:
    name: Dajanggan

  datasource:
    url: ${GOOGLE_DB_URL}
    username: ${GOOGLE_DB_USERNAME}
    password: ${GOOGLE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.dajanggan.domains
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL
    default-fetch-size: 100
    default-statement-timeout: 30
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    lazy-loading-enabled: false
    aggressive-lazy-loading: false

logging:
  level:
    root: INFO                           # 기본은 INFO
    com.dajanggan: INFO                  # 전체 INFO
    com.dajanggan.domain.metric.collector: DEBUG  # 수집기만 DEBUG
    org.apache.ibatis: WARN
    com.zaxxer.hikari: WARN

app:
  crypto:
    active-key-id: 1
    keys-v1: ${APP_CRYPTO_KEYS_V1}
    pbkdf2-iter: 200000
    salt-len: 16
    iv-len: 12

openai:
  api-key: ${OPENAI_API_KEY}
  model: gpt-4o-mini