spring:
  application:
    name: Dajanggan

  # .env import
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${GOOGLE_DB_URL}
    username: ${GOOGLE_DB_USERNAME}
    password: ${GOOGLE_DB_PASSWORD}

  # Redis 설정
  data:
    redis:
      host: localhost
      port: 6379
      password:



mybatis:

  # crypto 설정
  type-handlers-package: com.dajanggan.global.crypto.mybatis, com.dajanggan.global.config.mybatis

  # Mapper XML ??
  mapper-locations: classpath:mapper/**/*.xml

  # Type Alias ???
  type-aliases-package: com.dajanggan.domain.**.domain

  # MyBatis ??
  configuration:
    map-underscore-to-camel-case: true   # snake_case ? camelCase ?? ??
    jdbc-type-for-null: NULL             # NULL ?? ??
    default-fetch-size: 100              # ?? Fetch ??
    default-statement-timeout: 30        # ?? ???? (30?)
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl  # ??
    lazy-loading-enabled: false          # Lazy Loading ????
    aggressive-lazy-loading: false

# PostgreSQL
postgres:
  stats:
    reset-detection: true
    snapshot-interval: 300

logging:
  level:
    root: INFO                           # 기본은 INFO
    com.dajanggan: INFO                  # 전체 INFO
    com.dajanggan.domain.metric.collector: DEBUG  # 수집기만 DEBUG
    org.apache.ibatis: WARN
    com.zaxxer.hikari: WARN
server:
  port: 8080

app:
  crypto:
    active-key-id: 1
    keys-v1: ${APP_CRYPTO_KEYS_V1}
    pbkdf2-iter: 200000
    salt-len: 16
    iv-len: 12

openai:
  api-key: ${OPENAI_API_KEY}
  model: gpt-4o-mini
