spring:
  application:
    name: Dajanggan

  # .env import
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

mybatis:

  # crypto 설정
  type-handlers-package: com.dajanggan.global.crypto.mybatis

  # Mapper XML ??
  mapper-locations: classpath:mapper/**/*.xml

  # Type Alias ???
  type-aliases-package: com.dajanggan.domain.**.domain

  # MyBatis ??
  configuration:
    map-underscore-to-camel-case: true   # snake_case ? camelCase ?? ??
    jdbc-type-for-null: NULL             # NULL ?? ??
    default-fetch-size: 100              # ?? Fetch ??
    default-statement-timeout: 30        # ?? ???? (30?)
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl  # ??
    lazy-loading-enabled: false          # Lazy Loading ????
    aggressive-lazy-loading: false

# PostgreSQL
postgres:
  stats:
    reset-detection: true
    snapshot-interval: 300

logging:
  level:
    com.dajanggan: DEBUG
    com.dajanggan.domain.engine: DEBUG
    com.dajanggan.domain.query: DEBUG  # 추가: 쿼리 도메인 로깅
    org.apache.ibatis: DEBUG             # MyBatis ?? ??
    com.zaxxer.hikari: INFO              # HikariCP ??

server:
  port: 8080

app:
  crypto:
    active-key-id: 1
    keys-v1: ${APP_CRYPTO_KEYS_V1}
    pbkdf2-iter: 200000
    salt-len: 16
    iv-len: 12
